#!/usr/bin/env node
/* ══════════════════════════════════════════════════════════════════════════
   Birdie Design System — check-design.mjs   (VENDORED · drift gate)
   Verifies this app's vendored design-system files are byte-identical to the
   hashes recorded in .birdie-design.json (stamped at sync time from the
   canonical birdie-redesign source). Fails CI if anyone hand-edited a vendored
   file — those edits must be made in birdie-redesign and re-synced instead.

     node scripts/check-design.mjs

   GENERATED by birdie-redesign/sync-design.mjs — do not edit here.
   ══════════════════════════════════════════════════════════════════════════ */
import { createHash } from "node:crypto";
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
const manifestPath = resolve(root, ".birdie-design.json");

if (!existsSync(manifestPath)) {
  console.error("✗ .birdie-design.json not found — run the design sync from birdie-redesign.");
  process.exit(1);
}

const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
let drift = false;

for (const [rel, expected] of Object.entries(manifest.files ?? {})) {
  const p = resolve(root, rel);
  if (!existsSync(p)) {
    console.error(`✗ missing vendored file: ${rel}`);
    drift = true;
    continue;
  }
  const actual = createHash("sha256").update(readFileSync(p)).digest("hex");
  if (actual !== expected) {
    console.error(`✗ drift: ${rel} was edited locally (expected ${expected.slice(0, 12)}…, got ${actual.slice(0, 12)}…)`);
    drift = true;
  }
}

if (drift) {
  console.error(`\n✗ Birdie design-system drift. Vendored files are read-only; edit them in birdie-redesign\n  (source: ${manifest.source}) and run \`node scripts/sync-design.mjs\`, then commit the re-synced copies.`);
  process.exit(1);
}
console.log(`✓ Birdie design system in sync (canonical v ${manifest.version}).`);
